auth-server-uri: http://localhost:8181
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: kerdezz-client
            client-secret: mFu7u0kxmYCfDGRZHdQgNsZJCHSYci25
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, template.read, template.write

        provider:
          my-provider:
            issuer-uri: ${auth-server-uri}/realms/kerdezz-realm
  cloud:
    gateway:
      routes:
        - id: templateService
          uri: lb://template-service
          predicates:
            - Path=/api/templates/**
        - id: answerService
          uri: lb://answer-service
          predicates:
            - Path=/api/surveys/**
        - id: discoveryServer
          uri: lb://discovery-server
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discoveryServerStatic
          uri: lb://discovery-server
          predicates:
            - Path=/eureka/**
        - id: redirectToAccount
          uri: ${auth-server-uri}/realms/kerdezz-realm/account/?referrer=kerdezz-client#/
#          uri: ${auth-server-uri}/realms/kerdezz-realm/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:8080&client_id=kerdezz-client
          predicates:
            - Path=/kerdezz/account
          filters:
            - RedirectTo=302, ${auth-server-uri}/realms/kerdezz-realm/account/?referrer=kerdezz-client#/
        - id: redirectToAccount
          uri: ${auth-server-uri}/realms/kerdezz-realm/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:8080&client_id=kerdezz-client
          predicates:
            - Path=/kerdezz/logout
          filters:
            - RedirectTo=302, ${auth-server-uri}/realms/kerdezz-realm/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:8080&client_id=kerdezz-client
      default-filters:
        - TokenRelay=
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
