server:
  port: 8084
auth-server-uri: http://localhost:8181
spring:
  application:
    name: statistics-service
  cloud:
    stream:
      function:
        definition: surveyAnswerTopic
      bindings:
        surveyAnswerTopic-in-0:
          destination: surveyAnswerTopic
          group: surveyAnswerGroup
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server-uri}/realms/kerdezz-realm
  datasource:
    host: ${MSSQL_HOST:localhost}
    port: ${MSSQL_PORT:1433}
    database: surveyStatsDb
    url: jdbc:sqlserver://${spring.datasource.host}:${spring.datasource.port};database=${spring.datasource.database};encrypt=false
    username: SA
    password: P4SSw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
