auth-server-uri: http://localhost:8181
server:
  port: 8082
spring:
  application:
    name: template-service
    #spring.cloud.config.enabled=false
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: surveytemplatedb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server-uri}/realms/kerdezz-realm
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
