server:
  port: 8082
spring:
  application:
    name: template-service
    #spring.cloud.config.enabled=false
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: surveytemplatedb

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

