# Application
server:
  port: 8083
template-service-url: http://template-service/api/templates
auth-server-uri: http://localhost:8181
# Spring security
spring:
  application:
    name: answer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server-uri}/realms/kerdezz-realm
      client:
        registration:
          answer-service-client-credentials:
            provider: auth-server
            client-id: answer-service-client
            client-secret: qHZH0TVVkDhjmIEMenJlSeZAT1Qg93na
            authorization-grant-type: client_credentials
            client-name: answer-service-client-credentials
            scope: template.read
        provider:
          auth-server:
            issuer-uri: ${auth-server-uri}/realms/kerdezz-realm
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: answerdb
  cloud:
    stream:
      bindings:
        surveyAnswerSupplier-out-0:
          destination: surveyAnswerTopic
          group: surveyAnswerGroup

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
